# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji

# Site settings
url: 'https://assert.earth'
baseurl: ''
title: 'ASSERT: Second Responders'
description: 'Animal Survival & Safety Emergency Response Team'
permalink: pretty
logo: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=52"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: News
  url: /news/
- title: How You Can Help
  url: /how-you-can-help/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "ASSERT News & Updates"
    feature_text: |
      Animal Survival & Safety Emergency Response Blog
    feature_image: "https://picsum.photos/2560/600?image=866"
